### ISSUE TITLE
Reload error 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#117]
![image](https://user-images.githubusercontent.com/26451941/29699535-60e29e90-897f-11e7-85fe-8ba9abdbd512.png)

**Comment by hasan5151** [comment]
this is about hosting.

**Comment by AndroidAkyl** [comment]
So?

**Comment by hasan5151** [comment]
need to change host

**Comment by AndroidAkyl** [comment]
Let's change it then

**Comment by hasan5151** [comment]
need to buy host
