### ISSUE TITLE
Remove New Offers section 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#143]
![image](https://user-images.githubusercontent.com/26451941/32874487-ba2c1bec-cabc-11e7-90ea-75b240808702.png)

**Comment by hasan5151** [comment]
i tried this but couldnt find error. 
For coding it seems no error. I need to look all code

**Comment by AndroidAkyl** [comment]
Any progress on this issue @hasan5151 ?

**Comment by hasan5151** [comment]
now we have notifications
