### ISSUE TITLE
Put a Time column 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#152]
![image](https://user-images.githubusercontent.com/26451941/33205547-871854d4-d131-11e7-803d-ee06782c052e.png)

**Comment by hasan5151** [comment]
which time

**Comment by AndroidAkyl** [comment]
@hasan5151 by newest time - like real time- I just need to see when offers came to us - what time exactly, that way it will be easier for me to know which offers and when they came

**Comment by hasan5151** [comment]
you mean last offer send time?

**Comment by AndroidAkyl** [comment]
yes

**Comment by hasan5151** [comment]
we have now numbers of offers. We cant track time. Bcoz we didnt put this on db
