### ISSUE TITLE
Clone the web-system with a different URL

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#163]
Clone the web-system with a different URL 
URL name: strongbrain.info/tracks

**Comment by hasan5151** [comment]
explain this

**Comment by AndroidAkyl** [comment]
We need to clone web-system

**Comment by hasan5151** [comment]
for what?

**Comment by AndroidAkyl** [comment]
for entering the trucking industry

**Comment by hasan5151** [comment]
https://github.com/AndroidAkyl/VIP-Parts same
