### ISSUE TITLE
Edit the text and put stars so whatsapp will bold the text

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#165]
We need to edit the text , meaning we need to put stars to the text so whatsapp will make the text bold. 

Здравствуйте, это лучшие варианты, пожалуйста просмотрите :

Имя компании: *AvtoStroi*  <- here stars

ID заказа: *BNI1700864*  <- here stars,  *Название заказа:* - <- here stars  Радиатор для печки StepWagon RF3 *Количество:* - <- here stars  1  *цена:* - <- here stars  3150 *Дата доставки:* - <- here stars  Вчера

Итоговая цена: 3150
Доставка цена: 50
Итого : *3200* <- here stars

**Comment by hasan5151** [comment]
can you send me this text to my phone
