### ISSUE TITLE
Resend button for orders

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#174]
![image](https://user-images.githubusercontent.com/26451941/33793748-b302f7e0-dce7-11e7-872c-33d113670c38.png)
We need to implement this new button called : Resend 
Once operator clicks it the order should be resent using the same categories and subcategories.

This new feature is very important , cause we are starting to use the system of saving the sent orders in database, some clients ask to save the order and notify them once offers come, to do that we need this feature implemented ASAP. 

Name the button as: Переотправить

**Comment by hasan5151** [comment]
can you explain this detaily? will we resend orders to Vendors ? do we need new deadline?

**Comment by AndroidAkyl** [comment]
Yes , once I click that button , the order should be resent to vendors
