### ISSUE TITLE
User Hints for the web-app

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#179]
![image](https://user-images.githubusercontent.com/26451941/33929030-37461d0c-e012-11e7-8bc6-a802c654b01f.png)

**Comment by hasan5151** [comment]
![image](https://user-images.githubusercontent.com/17989735/34034676-9ec542ee-e1a9-11e7-8dba-c2fcac6eb7a7.png)
is it ok?

**Comment by AndroidAkyl** [comment]
This tooltip doesnt have next button? 
This User Hints should be regulated, it should have 3 buttons:
- Next
- Previous 
- End

**Comment by AndroidAkyl** [comment]
It should be like this: 
![image](https://user-images.githubusercontent.com/26451941/34035335-eab9f04e-e1ab-11e7-84e1-f49091baa6c2.png)

**Comment by AndroidAkyl** [comment]
You can use the library here I think:  https://introjs.com/

**Comment by hasan5151** [comment]
what you want exactly hints or interactive buttons?

**Comment by AndroidAkyl** [comment]
I want this : https://introjs.com/

**Comment by hasan5151** [comment]
https://github.com/AndroidAkyl/Web-App/issues/181 same
