### ISSUE TITLE
If an item was Basketed (sent to basket) then the Basket button should change its color 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#184]
![image](https://user-images.githubusercontent.com/26451941/34202302-9aaf7eee-e5a1-11e7-9011-68bc7a912170.png)
If an item was Basketed (sent to basket) then the Basket button should change its color

**Comment by hasan5151** [comment]
what color do you want? finished

**Comment by AndroidAkyl** [comment]
Red will be good I think
