### ISSUE TITLE
Add a button to download pdf of the basket 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#187]
![image](https://user-images.githubusercontent.com/26451941/34246652-b32c9232-e659-11e7-97d0-af3833fdce95.png)
We need this URGENTLY, cause we have to send out pdf files as offers for AMSs, without this we look very unprofessional.

**Comment by hasan5151** [comment]
Select text - right click - print - save as pdf

**Comment by AndroidAkyl** [comment]
[test.pdf](https://github.com/AndroidAkyl/Web-App/files/1579347/test.pdf)
Yes we can do it that way but that way does not look professional and AMSs dont like it that way, it should be in table.
