### ISSUE TITLE
Add column of categories of cars 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#196]
![image](https://user-images.githubusercontent.com/26451941/36827841-3248e968-1d40-11e8-93a1-065786c23b3d.png)
We need to see which vendors sells what cars

**Comment by hasan5151** [comment]
![image](https://user-images.githubusercontent.com/17989735/37149444-2b73cc94-22f8-11e8-8b34-252204c6d879.png)
click row and see. Only vendors who updated app will show. Others neeeds to update

**Comment by AndroidAkyl** [comment]
This issue should have been implemented the other way, this way its not helpful at all to be honest. 
The cars should have been shown in a column, and if operator searches for some particular cars then the database should respond to the search query.
