### ISSUE TITLE
I dont have button should send data to us 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#197]
I dont have button should send data to us

**Comment by hasan5151** [comment]
for what?

**Comment by AndroidAkyl** [comment]
Once vendors click the I dont have button then we should get some response , this way we can see who has parts and does not, and we will not call vendors who does not have parts, currently we are calling all the vendors to find out if they have parts or not, and this is taking so much time, and some vendors are complaining that we are disturbing them a lot, thats why we need to see who clicked the I dont have button.
