### ISSUE TITLE
Impossibility to send long length messages 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#53]
![image](https://cloud.githubusercontent.com/assets/26451941/26442846/f81f35fe-4157-11e7-86ab-d905d6b9abd7.png)
We need to be able to send long lenght messages, because we will be sending guides on how to use the app.

**Comment by AndroidAkyl** [comment]
![image](https://cloud.githubusercontent.com/assets/26451941/26482276/6e0ffbbc-4208-11e7-8d80-c7fd58fb7c46.png)
Issue is still actual

**Comment by hasan5151** [comment]
working clear cache http://strongbrain.info/autoparts/sendTips.html

**Comment by AndroidAkyl** [comment]
![image](https://cloud.githubusercontent.com/assets/26451941/26487256/937d6e76-4220-11e7-9a8f-055ee1ddfa46.png)
Even with the direct link its not working @hasan5151

**Comment by hasan5151** [comment]
bcoz of russian letters fixed
