### ISSUE TITLE
50 som per delivery add to the database - Order History 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#55]
Add delivery money to the document

**Comment by hasan5151** [comment]
can you explain this one? i didnt understand exactly

**Comment by AndroidAkyl** [comment]
Sure, just add delivery money , for every delivery we will take 50 som.
For example, if the total money of items equals tothe 500 som, then just
add delivery money 50 som, in total 550 som.
But we need to write this delivery money separately - on the bottom of the
document.

Like:
Total:500
Delivery : 50
And that's it
