### ISSUE TITLE
Generate new password button 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#58]
Здравствуйте, это ваш новый пароль : 
Мы рады что вы с нами ;)

**Comment by hasan5151** [comment]
ref.changePassword({
  email       : "bobtony@firebase.com",
  oldPassword : "correcthorsebatterystaple",
  newPassword : "neatsupersecurenewpassword"
});

we must know his old password.

**Comment by AndroidAkyl** [comment]
@hasan5151 right

**Comment by AndroidAkyl** [comment]
How this will work, steps: 
1. Operator receives a request from vendors
2. Operator checks for confirmation-phone number, name and etc..
3. Operator opens up New Vendor section to find the vendor 
4. Operator opens up vendor's info , here : 
when operator clicks on someone's info/line/row - a window should appear with Generate password button on it 
5. Operator enters the old password of the vendor and clicks Generate Password button 
6. Then new password gets generated with default text : 
Здравствуйте, это ваш новый пароль : `here new password`
Мы рады что вы с нами ;)
7. Operator copies the text and sends it to the Vendor.

**Comment by hasan5151** [comment]
for testing use we@we.com or create new account and update the app
