### ISSUE TITLE
Send strings for translation  - use Slack 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#59]

**Comment by hasan5151** [comment]
sent to Slack

**Comment by AndroidAkyl** [comment]
<string name="sendMail">Отправить на почту </string>
    <string name="itemName">Название заказа :</string>
    <string name="deadline">Крайний срок :</string>
    <string name="bidSupport">Bid поддержка </string>

@hasan5151 what about strings for the web-app?

**Comment by AndroidAkyl** [comment]
also check the slack
