### ISSUE TITLE
Sub-categories 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#75]
1. Амортизаторы багажника и капота

2. Амортизаторы, пружины, опоры, пыльники, отбойники

3. Двигатель

4. Детали кузова

5. Масла, смазки и герметики

6. Подвеска двигателя, трансмиссии

7. Подвеска задняя

8. Подвеска передняя

9. Ремни, ролики

10. Рулевое управление

11. Система охлаждения и кондиционирования

12. Ступицы и подшипники

13. Топливная система

14. Тормозная система

15. Трансмиссия, сцепление

16. Фильтры

17. Электроника, зажигание, стартер, генератор

18. Оптика

19. Детали внутренней отделки

20. Выхлопная система

21. Электроника, зажигание, стартер, генератор

**Comment by hasan5151** [comment]
17,21 are they same sub? if same i will delete 21
