### ISSUE TITLE
Domain strongbrain.info expires at 2017-07-06

### ISSUE THREAD

**Issue by hasan5151** [AndroidAkyl/Web-App#78]
http://www.hoster.kg/

**Comment by AndroidAkyl** [comment]
thanks for info @hasan5151

**Comment by hasan5151** [comment]
btw we need to buy host

**Comment by AndroidAkyl** [comment]
Buy host ? Why? Don't we have one already ?

**Comment by hasan5151** [comment]
i think Sam bought hosting. When will it expire i dont know

**Comment by hasan5151** [comment]
ЭТО СООБЩЕНИЕ СГЕНЕРИРОВАНО АВТОМАТИЧЕСКИ, ОТВЕЧАТЬ НА НЕГО НЕ ТРЕБУЕТСЯ.
ВОПРОСЫ ПО ПРОДЛЕНИЮ ДОМЕНА НЕОБХОДИМО ОТПРАВЛЯТЬ НА УКАЗАННЫЕ НИЖЕ КОНТАКТЫ ПАРТНЕРА.

Здравствуйте,

Срок делегирования домена strongbrain.info ИСТЁК 06.07.2017.

Домен был снят с делегирования!


Администратором домена является Asylbek Esenaliyev.
Домен находится под управлением нашего партнера:
Ершов Сергей Владимирович http://www.hoster.kg/
E-mail: hoster@hoster.kg
Тел.: +996 312 691933
Время работы: круглосуточно

Для продления срока регистрации домена Вам необходимо обратиться в службу поддержки указанного партнера (Ершов Сергей Владимирович).

Если Вы желаете продлить срок регистрации домена, то Вам необходимо до 05.08.2017
подать и оплатить заявку на продление домена, иначе 05.08.2017 домен будет
автоматически удален из реестра!

Также уведомляем Вас о необходимости проверки актуальности хранящихся в Реестре сведений об администраторе домена.

* * *

THIS IS AUTOMATICALLY GENERATED MESSAGE, PLEASE DO NOT RESPONSE ON IT.
PLEASE SENT ALL QUESTIONS ABOUT DOMAIN RENEWAL TO THE FOLLOWING PARTNER'S CONTACTS.

Domain strongbrain.info EXPIRES on 2017-07-06.
Domain delegation has been cancelled!

Domain administrator is Asylbek Esenaliyev.
Domain is under control of our partner:
Ершов Сергей Владимирович http://www.hoster.kg/
E-mail: hoster@hoster.kg
Phone: +996 312 691933
Operation hours: круглосуточно


To prolong your domain delegation you have to contact the partner (Ершов Сергей Владимирович).

If you want to prolong the domain you need to submit and pay an application for renewal of the domain till 2017-08-05,
otherwise the domain name will be automatically deleted from registry on 2017-08-05
!

Please also be advised that you obligated to review the contact information associated with your domain names
and make corrections whenever necessary.

--
С уважением,
служба поддержки ООО "Регтайм"
