### ISSUE TITLE
When the first window of categories is clicked and if user clicks back button the whole page reloads 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#79]

**Comment by AndroidAkyl** [comment]
![screenshot_2017-06-09-10-34-01](https://user-images.githubusercontent.com/26451941/26961285-7474fb7c-4cff-11e7-8631-88b3314c6bd1.png)

**Comment by hasan5151** [comment]
this is for renew badge

**Comment by AndroidAkyl** [comment]
Ok so this was purposely made so ?

**Comment by hasan5151** [comment]
yes
