### ISSUE TITLE
Assign IDs for vendors 

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#90]
0001

**Comment by AndroidAkyl** [comment]
![image](https://user-images.githubusercontent.com/26451941/27273309-583b805e-54f0-11e7-9884-b100d7e1f68f.png)
Add ID column, so we can see in case of need Vendor's IDs

**Comment by hasan5151** [comment]
vendor can get vendor id now only at beta

**Comment by AndroidAkyl** [comment]
@hasan5151 right, thats ok, but we need to add the USER ID column anyway, so we will be able to see clearly in the future.
