### ISSUE TITLE
Order is closed automatically before its status has been chosen

### ISSUE THREAD

**Issue by AndroidAkyl** [AndroidAkyl/Web-App#94]
![image](https://user-images.githubusercontent.com/26451941/27273890-dea0530c-54f2-11e7-8175-f204acdf12a8.png)
Order cannot be closed until its status is chosen and until Close Order button is clicked.

**Comment by hasan5151** [comment]
this is the best way for this. Otherwise it gives error.
If operator doesnt select anything db will not  affected
if he press X button page will be refresh

**Comment by AndroidAkyl** [comment]
ok
